//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_BANHANG_AZURE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_SP
    {
        public MENU_SP()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public System.Guid MN_ID { get; set; }
        public string MN_NHOM { get; set; }
        public string MN_LOAI { get; set; }
        public string MN_MOTA { get; set; }
        public Nullable<int> MN_STT { get; set; }
    
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
