//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_BANHANG_AZURE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public System.Guid SP_ID { get; set; }
        public Nullable<System.Guid> MN_ID { get; set; }
        public string SP_MA { get; set; }
        public string SP_TEN { get; set; }
        public string SP_TENTM { get; set; }
        public string SP_DVT { get; set; }
        public string SP_URLANH { get; set; }
        public Nullable<decimal> SP_GIABAN { get; set; }
        public Nullable<int> SP_LUOTXEM { get; set; }
        public string SP_MOTA { get; set; }
        public string SP_DTKT { get; set; }
        public Nullable<System.DateTime> SP_NGAYTAO { get; set; }
        public string SP_NHACC { get; set; }
        public string SP_MAUSAC { get; set; }
        public string SP_URLANH1 { get; set; }
        public string SP_URLANH2 { get; set; }
        public string SP_URLANH3 { get; set; }
        public Nullable<int> SP_STT { get; set; }
    
        public virtual MENU_SP MENU_SP { get; set; }
    }
}
